### PR TITLE
Add some 'code change' annotations to Day 59

### PR DESCRIPTION
**Pull request by sir-pinecone**
I personally find this metadata to be useful. If you don't mind then I'll continue to submit PRs as I make my way through the vids!

### CODE REVIEW

**Comment by AndrewJDR** [comment]
Hey! I'm not really an active maintainer here these days, but I still try to keep my eyes peeled on this project. I think your help and contributions on this kind of thing will be very welcome, but I've heard some rumblings that there is / will be a certain syntax for this kind of metadata which @miblodelcarpio and crew can perhaps provide more details about... I'm sure he will chime in soon enough!

**Comment by miblodelcarpio** [comment]
Cheers for this, @sir-pinecone! These days I'd annotate this stuff with a separate annotation for the code change, as Casey starts working on it. You can see this happening [here](https://github.com/HandmadeCompanion/HandmadeCompanion/blame/master/src/documents/videos/code/day071.html.md#L51) on day071 and more recently [here](https://github.com/HandmadeCompanion/HandmadeCompanion/blame/master/src/documents/videos/code/day390.html.md#L56) on day390. Would this be good for you, @sir-pinecone? 

If so, would you be more comfortable writing an annotation in this format for me to review and potentially merge as-is; or would you rather write a placeholder annotation to alert me to a needed addition, where I can write a new one and close your PR? Another option would be commenting on the day's issue, e.g. [this one for day059](https://github.com/HandmadeCompanion/HandmadeCompanion/issues/57), mentioning the timecode that a new annotation is needed. Personally, an issue comment may actually be my favourite, because I think that'd give you less work (no need to pull the repo or bother about writing a syntactically valid annotation), and I would also probably want to do an edit pass over the Qs anyway, for typos and emoticons and things that I tend to "fix".

I will need to go back over at least some of the days to prep the stuff for the new system, so your contributions are indeed very welcome!

And yeah, the metadata of the new system alluded to by @AndrewJDR is the notion of "media tagging", where media are things like "programming", "chat comment", "blackboard", "in-game". So, in this new system, this section would have all the chat comments tagged "chat comment" (naturally!), with a new annotation for the code change being tagged "programming". This may all be filtered too, which you can try out [here](http://test.miblodelcarpio.co.uk/).

Less us know what you fancy doing, and cheers again for your help!

**Comment by sir-pinecone** [comment]
Hey @miblodelcarpio, thanks for the detailed response. Your new annotation system looks wicked! I love that you can filter by annotation types. Also this is the first I've seen RISCY BUSINESS...sigh, I wonder what I can cut out of my day in order to follow this project too hah. Side question - do you need any assistance with the new annotation system? I did web development (JS, CSS, backend, ClojureScript, React, etc) for about 8 years so I may be able to take on some tasks depending on the scope. Is there a Github project tracking the work?

---

Regarding the topic at hand:

`These days I'd annotate this stuff with a separate annotation for the code change, as Casey starts working on it....Would this be good for you, @sir-pinecone?`

Yes, that looks good!

I really don't mind submitting proper PRs with an annotation edit, but I understand why you want to do an edit pass. If you really don't mind opening up the vid and typing it yourself then I'll use your favourite method and create an issue to flag the video. 

Cheers!

**Comment by sir-pinecone** [comment]
I'm going to close this and comment on an issue instead.

**Comment by miblodelcarpio** [comment]
Cheers, @sir-pinecone! Yeah, RISCY BUSINESS is really cool, and I think brings another slice of uniqueness in addition to those which Handmade Hero brings: it documents a developer's learning process from scratch, with plenty of research, advice seeking and even, at times, recommendations of improvements / clarifications to specs (thanks to the RISC-V tech being pretty darn fresh).

There is a repo for the new system [here](https://git.handmade.network/Annotation-Pushers/Annotation-System). Next up I'll be working on the issues for the so-called [Project Edition](https://git.handmade.network/Annotation-Pushers/Annotation-System/milestones/2), but that has to wait until I've built a new computer (this laptop is failing, hence any delays and the Handmade Hero days starting to pile up a little, etc.). So far I feel like my engagement with the web dev side of it has been lessened thanks especially to the help of @AsafGartner and his player which I more or less just had to copy and paste, but maybe as I start to work through the searching stuff I'll realise that I need to get more deeply involved with it, possibly some nifty nginx stuff. But we'll have to see.

And thank you for your comment on issue #57! Handling it now (laptop failure permitting).

**Pull request closed without merging**
